name: Main branch
on:
  push:
    branches: [main]
jobs:
  publish:
      name: Publish
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run unit and intergration tests.
          run: cargo publish --token ${{ secrets.CRATES_API_KEY }}

  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Updated BundleBee #dev #rust https://github.com/xxninjabunnyxx/bundlebee"
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_BEARER_TOKEN }}