name: Main branch
on:
  push:
    branches: [main]
jobs:
  publish:
      name: Publish
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Run unit and intergration tests.
          run: cargo publish --token ${{ secrets.CRATES_API_KEY }}