name: Publish and Tweet
on:
  push:
    branches: [main]
jobs:
  publish:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Publish Crate.
          run: cargo publish --token ${{ secrets.CRATES_API_KEY }}
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    #needs: publish
    steps:
      - uses: Eomm/why-don-t-you-tweet@v1
        with:
          tweet-message: "Updated BundleBee #dev #rust https://github.com/xxninjabunnyxx/bundlebee"
        env:
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
